sudo: false
language: python
dist: xenial  # required for Python >= 3.7
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

matrix:
  allow_failures:
    # - python: 3.9-dev  # allow tests to fail with this pre-release of Python

install: pip install tox-travis
script: tox
