name: '[codecov]'

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.6' ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install depdencies
      run: |
        python -m pip install pytest pytest-cov
    - name: Run cov
      run: |
        pytest --cov=neuroglancer_scripts --cov-report=xml
    - uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)
