# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Publish release to pypi

on:
  release:
    types:
      - created

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Build the package
      run: |
        echo "Installing and upgrading build and twine"
        python3 -m pip install --user --upgrade build twine
        echo "Package the project"
        python3 -m build
    - name: Prepare pypi settings
      run: |
        echo "[pypi]" >~/.pypirc
        echo "username = __token__" >>~/.pypirc
        echo "password = ${{ secrets.PYPI_PUSH }}" >>~/.pypirc
    - name: Upload to pypi
      run: |
        echo "Uploading to pypi"
        python -m twine upload dist/*
